### ISSUE TITLE
git@github.com: Permission denied (publickey)

### ISSUE THREAD

**Issue by arpu** [blaze33/droneWorld#2]
``[1/4]` Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git@github.com:blaze33/ShaderParticleEngine.git
Directory: /home/arpu/Work/githubsources/droneWorld
Output:
git@github.com: Permission denied (publickey).
fatal: Konnte nicht vom Remote-Repository lesen.
``

looks like better use the normal https://github.com/blaze33/ShaderParticleEngine.git#d2df4b8a9ee97af8f282daa61911e47cff86d488
link

**Comment by arpu** [comment]
https://github.com/blaze33/droneWorld/pull/3

**Comment by blaze33** [comment]
Closed by PR #3
